Ecomerce/Eticaret/Models/Context/DbTradeContext.cs
using Eticaret.Models.Entities;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace Eticaret.Models.Context
{
    public class DbTradeContext:DbContext
    {
        public DbTradeContext()
        {
            Database.Connection.ConnectionString = "server=DESKTOP-CHSJJ4J\\SQLEXPRESS;database=DbTrade;Trusted_Connection=true;";
        }
        public DbSet<Product> Products { get; set; }
        public DbSet<Order> Orders { get; set; }
        public DbSet<Customer> Customers { get; set; }
        public DbSet<Category> Categories { get; set; }
        public DbSet<ProductCategories> ProductCategories { get; set; }
    }
}

Ecomerce/Eticaret/Models/Entities/Category.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Eticaret.Models.Entities
{
    public class Category
    {
        public int Id { get; set; }
        public string CategoryName { get; set; }
        public virtual List<ProductCategories> ProductCategories { get; set; }
    }
}

Ecomerce/Eticaret/Models/Entities/Customer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace Eticaret.Models.Entities
{
    public class Customer
    {
        public Customer()
        {
            IsActive = false;
        }
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public bool IsActive { get; set; }
        public Guid ActivationKey { get; set; }
    }
}

Ecomerce/Eticaret/Models/Entities/Order.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Eticaret.Models.Entities
{
    public class Order
    {
        public Order()
        {
            OrderDate = DateTime.Now;
        }
        public int Id { get; set; }
        public DateTime OrderDate { get; set; }
        public int Quantity { get; set; }

        public int ProductId { get; set; }
        public int UserId { get; set; }
        public virtual Product Product { get; set; }
        public virtual Customer User { get; set; }
    }
}

Ecomerce/Eticaret/Models/Entities/Product.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Eticaret.Models.Entities
{
    public class Product
    {
        public int Id { get; set; }
        public string ProductName { get; set; }
        public int UnitInStock { get; set; }
        public string UnitPrice { get; set; }
        public virtual List<ProductCategories> ProductCategories { get; set; }
    }
}

Ecomerce/Eticaret/Models/Entities/ProductCategories.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Eticaret.Models.Entities
{
    public class ProductCategories
    {
        public int CategoryId { get; set; }
        public int ProductId { get; set; }
        public virtual Category Category { get; set; }
        public virtual Product Product { get; set; }
    }
}

Ecomerce/Eticaret/Controllers/HomeController.cs
using Eticaret.Filters;
using Eticaret.Models.Context;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Eticaret.Controllers
{
    [AuthorizationHomeFilter]
    public class HomeController : Controller
    {
        DbTradeContext dbTradeContext = new DbTradeContext();
        // GET: Home
        public ActionResult Index()
        {
            return View(dbTradeContext.Products.ToList());
        }
       


    }
}

Ecomerce/Eticaret/Controllers/LoginController.cs
using Eticaret.Filters;
using Eticaret.Models.Context;
using Eticaret.Models.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Eticaret.Controllers
{
    [AuthorizationLoginFilter]
    public class LoginController : Controller
    {
        DbTradeContext DbTradeContext = new DbTradeContext();
        // GET: Login
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(Customer customer)
        {
            Customer _customer = DbTradeContext.Customers.SingleOrDefault(x => x.UserName == customer.UserName && x.Password == customer.Password);
            ActionResult actionResult;
            if (_customer != null)
            {
                if (_customer.IsActive!=false)
                {
                    Session["User"] = _customer;
                    actionResult = RedirectToAction("Index", "Home");
                }
                else
                {
                    TempData["BasarisizGiris"] = "Hesabınız Onaylanmamış. Eposta Adresinize Giderek Hesabınızı Onaylayın.";
                    actionResult = View();
                }
            }
            else
            {
                TempData["BasarisizGiris"] = "Kullanıcı Adı veya Parolanız Yanlış.";
                actionResult = View();
            }
            return actionResult;
        }

    }
}

Ecomerce/Eticaret/Controllers/ProductCategoriesController.cs
using Eticaret.Models.Context;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Eticaret.Controllers
{
    public class ProductCategoriesController : Controller
    {
        DbTradeContext dbTradeContext = new DbTradeContext();
        // GET: ProductCategories
        public PartialViewResult _Categories()
        {
            return PartialView(dbTradeContext.Categories.ToList());
        }
       

        
    }
}

Ecomerce/Eticaret/Controllers/RegisterController.cs
using Eticaret.Filters;
using Eticaret.Models.Context;
using Eticaret.Models.Entities;
using Eticaret.Utils;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;

namespace Eticaret.Controllers
{
    [AuthorizationLoginFilter]
    public class RegisterController : Controller
    {
        DbTradeContext dbTradeContext = new DbTradeContext();
        // GET: Register
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(Customer customer)
        {
            Guid guid = Guid.NewGuid();
            customer.ActivationKey = guid;
            dbTradeContext.Customers.Add(customer);
            dbTradeContext.SaveChanges();
            MailSender.GmailMessage(customer.Email, "Üyelik Aktivasyonu", $"http://localhost:56944/Register/AktivationApprove/{guid}");
            return View("MailAktivasyon");
        }


        public ActionResult MailAktivasyon()
        {
            return View();
        }

        
        public ActionResult AktivationApprove(Guid id)
        {
            bool kontrol = dbTradeContext.Customers.Any(x=>x.ActivationKey==id);
            if (kontrol)
            {
                Customer customer = dbTradeContext.Customers.SingleOrDefault(x=>x.ActivationKey==id);
                customer.IsActive =true;
                dbTradeContext.Entry(customer).State = EntityState.Modified;
                dbTradeContext.SaveChanges();
                TempData["UyelikOnaylandi"] = "Üyeliğiniz Onaylandı. Giriş Yapabilirsiniz.";
                return RedirectToAction("Index", "Login");
            }
            else
            {
                TempData["GecersizAktivasyonLinki"] = "Aktivasyon Linki Geçersiz Veya Süresi Dolmuş.";
                Thread.Sleep(3000);
                return View();
            }
            
        }
        
        
        
    }
}

Ecomerce/Eticaret/Controllers/SharedController.cs
using Eticaret.Models.Context;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Eticaret.Controllers
{
    public class SharedController : Controller
    {
        DbTradeContext dbTradeContext = new DbTradeContext();
        // GET: Shared
        public ActionResult Index()
        {
            return View();
        }

        public PartialViewResult Categories()
        {
            return PartialView();
        }
    }
}

Ecomerce/Eticaret/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<p>asdsakdksa sdk askd kasd as dkask dkas dkask dkaskd kas dkask dkas</p>

Ecomerce/Eticaret/Views/Login/Index.cshtml
@model Eticaret.Models.Entities.Customer
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
</head>
<body>
    <div>
        @if (TempData["UyelikOnaylandi"] != null)
        {
            <div class="row bg-primary text-white">@TempData["UyelikOnaylandi"]</div>
        }
        @if (TempData["BasarisizGiris"] != null)
        {
            <div class="row bg-danger text-white">@TempData["BasarisizGiris"]</div>
        }
        <div class="row">
            <form method="post">
                @Html.Label("Kullanıcı Adı")
                @Html.TextBoxFor(x => x.UserName, new { @class = "form-control" })
                @Html.Label("Parola")
                @Html.TextBoxFor(x => x.Password, new { @class = "form-control" })
                <button class="btn btn-success">Giriş Yap</button>
            </form>
        </div>
    </div>
</body>
</html>

Ecomerce/Eticaret/Views/ProductCategories/_Categories.cshtml
@model List<Eticaret.Models.Entities.Category>

@foreach (Eticaret.Models.Entities.Category item in Model)
{
    <ul class="navbar-brand">
        <li class="nav-item">
            <a class="nav-link" href="/ProductCategories/_Categories/@item.Id">@item.CategoryName</a>
        </li>
    </ul>
}

Ecomerce/Eticaret/Views/Register/AktivationApprove.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>AktivationApprove</title>
</head>
<body>
    <div> 
        @if (TempData["GecersizAktivasyonLinki"]!=null)
        {
            @TempData["GecersizAktivasyonLinki"].ToString()
        }
    </div>
</body>
</html>

Ecomerce/Eticaret/Views/Register/Index.cshtml
@model Eticaret.Models.Entities.Customer
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    
</head>
<body>
    <div> 
        <form method="post">
            @Html.Label("First Name")
            @Html.TextBoxFor(x => x.FirstName, new { @class = "form-control" })
            @Html.Label("Last Name")
            @Html.TextBoxFor(x => x.LastName, new { @class = "form-control" })
            @Html.Label("Email")
            @Html.TextBoxFor(x => x.Email, new { @class = "form-control" })
            @Html.Label("User Name")
            @Html.TextBoxFor(x => x.UserName, new { @class = "form-control" })
            @Html.Label("Password")
            @Html.TextBoxFor(x => x.Password, new { @class = "form-control" })
            <button class="btn btn-primary">Üye Ol</button>
        </form>
    </div>
</body>
</html>

Ecomerce/Eticaret/Views/Register/MailAktivasyon.cshtml
<p class="">Üyelik Aktifleştirme, Eposta Adresinize Gönderildi.</p>
<p><a href="https://mail.google.com/">Eposta Kontrolü</a></p>

Ecomerce/Eticaret/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>E-Ticaret Home</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!-- Bootstrap CSS -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="#"><h2 class="text-warning">E-Ticaret</h2></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mob-navbar" aria-label="Toggle">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="mob-navbar">
                <ul class="navbar-nav mb-2 mb-lg-0 mx-auto">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#">Home</a>
                    </li>
                </ul>
                <form class="d-flex">
                    <input class="form-control me-2" type="text" placeholder="Username" />
                    <input class="form-control me-2" type="password" placeholder="Password" />
                    <button class="btn btn-warning" type="submit">Login</button>
                    <button class="btn btn-danger">Register</button>
                </form>
            </div>
        </div>
    </nav>
    <div class="container">
        <div class="row">
            <div class="col-md-2">
                <h5>Kategoriler</h5>
                @Html.Action("_Categories","ProductCategories")

            </div>
            <div class="col-md-10">
                @RenderBody()
            </div>
        </div>
    </div>

    <script src="~/Scripts/bootstrap.bundle.min.js"></script>
</body>
</html>